### ISSUE TITLE
v2 Support

### ISSUE THREAD

**Issue by pyro2927** [Calyhre/dribbble#11]
[Dribbble is updating their API to v2](http://developer.dribbble.com/v2/).  Excerpt from their most recent email:

> In particular, we’ve seen a growing number of applications that violate our terms and continue to do so even when notified. Over the past months we’ve spent tremendous effort to suspend apps that are malicious in nature and/or break our API terms of use, but we've concluded that this isn't the best use of our resources towards advancing the Dribbble design community. The costs simply outweigh the benefits. As such, we’ve made the difficult decision to scale back the API and **v1 will be retired on March 26, 2018**.

Looks like there are a few differences around Teams and Buckets.

**Comment by Calyhre** [comment]
Fixed in #13, very sorry for the very long no-response.
