### ISSUE TITLE
Teams Shots

### ISSUE THREAD

**Issue by dangodev** [Calyhre/dribbble#6]
Would it be possible to add support for Team shots (http://developer.dribbble.com/v1/teams/members/)? I’d love to add it myself but I’m a bit out of my depth with how to contribute to the extension.

**Comment by Calyhre** [comment]
Hi, take a look at #5 I've add most of the API endpoints. It's available in Rubygems with the version `1.0.0.beta1`.
Just missing the documentation for now. What do you want with the team shots ?

**Comment by dangodev** [comment]
I think it’s a relatively-new addition to the Dribbble API. With this gem I can see all the teams a user is a member of, but I want to get all shots from a team account (i.e., `https://api.dribbble.com/v1/teams/549432/shots`). I didn’t see it in #5; did I miss something?

**Comment by Calyhre** [comment]
You're right!




It's been a long since #5 is open, let's finish it. Please be patiente, I'll ping you on it when it's ready.


--
charley_david

**Comment by dangodev** [comment]
Great! Thanks!

**Comment by Calyhre** [comment]
Hey! I just add teams support on the `1.0.0.beta2` version :)

Now, you can ask for team members and shots like this:

```ruby
token = ...
user = Dribbble::User.find(token, 'Drubbbly')
team = user.teams.first
team.members # Return all the team members

**Comment by Calyhre** [comment]
Forget about the `.beta2`, `v1.0.0` is out!

**Comment by dangodev** [comment]
Awesome! Really excited for this!
